# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: test
        run: go test -race -covermode=atomic -v ./...
